x = vector("numeric", 10)
print("Numeric Type:")
print(x)
c = vector("complex", 10)
print("Complex Type:")
print(c)
l = vector("logical", 10)
print("Logical Type:")
print(l)
chr = vector("character", 10)
print("Character Type:")
print(chr)

x = c(10, 20, 30, 40, 50)
print("Original Vectors:")
print(x)
print("Sort in ascending order:")
print(sort(x))
print("Sort in descending order:")
print(sort(x, decreasing=TRUE))

myList <- list('A' = 2, 'B' = 3, 'C' = 7,'D'=9)
myvector <-(myList, function(x) x)

A=Matrix=(c(2,0,1.3),ncol=2)
B=Matrix=(c(5,2,4,-1),ncol=2)
print(A+B)
print(A-B)